chore: bump version to 1.1.0 [skip ci]

diff --git a/roulette b/roulette
--- a/roulette
+++ b/roulette
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 0.8.4 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.3.5 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n"
+if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
+  printf "bash version 4.2 or higher is required\n" >&2
   exit 1
 fi
 
@@ -242,68 +242,61 @@ version_command() {
 
 # :command.usage
 roulette_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "roulette - Play random video files from a directory\n"
-    echo
+  printf "roulette - Play random video files from a directory\n\n"
 
-  else
-    printf "roulette - Play random video files from a directory\n"
-    echo
-
-  fi
-
-  printf "Usage:\n"
-  printf "  roulette [DIRECTORY] [options]\n"
+  printf "%s\n" "Usage:"
+  printf "  roulette [DIRECTORY] [OPTIONS]\n"
   printf "  roulette --help | -h\n"
   printf "  roulette --version | -v\n"
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
-    printf "Options:\n"
-
-    # :command.usage_fixed_flags
-    echo "  --help, -h"
-    printf "    Show this help\n"
-    echo
-    echo "  --version, -v"
-    printf "    Show version number\n"
-    echo
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "Options:"
 
     # :command.usage_flags
     # :flag.usage
-    echo "  --debug, -d"
+    printf "  %s\n" "--debug, -d"
     printf "    Enable debug mode\n"
     echo
 
     # :flag.usage
-    echo "  --reset"
+    printf "  %s\n" "--reset"
     printf "    Empty playlist and rescan directory\n"
     echo
 
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+    printf "  %s\n" "--version, -v"
+    printf "    Show version number\n"
+    echo
+
     # :command.usage_args
-    printf "Arguments:\n"
+    printf "%s\n" "Arguments:"
 
     # :argument.usage
-    echo "  DIRECTORY"
+    printf "  %s\n" "DIRECTORY"
     printf "    Path to search for video files\n"
     echo
 
     # :command.usage_environment_variables
-    printf "Environment Variables:\n"
+    printf "%s\n" "Environment Variables:"
 
     # :environment_variable.usage
-    echo "  ROULETTE_DEBUG"
+    printf "  %s\n" "ROULETTE_DEBUG"
     printf "    Enable debug mode\n"
     echo
 
     # :environment_variable.usage
-    echo "  MPV_GEOMETRY"
+    printf "  %s\n" "MPV_GEOMETRY"
     printf "    Set default window positioning (e.g., '+0+0')\n"
     echo
 
     # :environment_variable.usage
-    echo "  MPV_VOLUME"
+    printf "  %s\n" "MPV_VOLUME"
     printf "    Set default volume (0-100)\n"
     echo
 
@@ -311,12 +304,16 @@ roulette_usage() {
 }
 
 # :command.normalize_input
+# :command.normalize_input_function
 normalize_input() {
-  local arg flags
+  local arg passthru flags
+  passthru=false
 
   while [[ $# -gt 0 ]]; do
     arg="$1"
-    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+    if [[ $passthru == true ]]; then
+      input+=("$arg")
+    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
       input+=("${BASH_REMATCH[1]}")
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -327,6 +324,9 @@ normalize_input() {
       for ((i = 0; i < ${#flags}; i++)); do
         input+=("-${flags:i:1}")
       done
+    elif [[ "$arg" == "--" ]]; then
+      passthru=true
+      input+=("$arg")
     else
       input+=("$arg")
     fi
@@ -334,22 +334,36 @@ normalize_input() {
     shift
   done
 }
+
 # :command.inspect_args
 inspect_args() {
-  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
+  local k
+
   if ((${#args[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
-    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
   else
     echo args: none
   fi
 
-  if ((${#other_args[@]})); then
+  if ((${#deps[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
-    echo other_args:
-    echo "- \${other_args[*]} = ${other_args[*]}"
-    for i in "${!other_args[@]}"; do
-      echo "- \${other_args[$i]} = ${other_args[$i]}"
+    echo deps:
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
+  fi
+
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
     done
   fi
 }
@@ -358,20 +372,35 @@ inspect_args() {
 
 # :command.parse_requirements
 parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
-  case "${1:-}" in
-    --version | -v)
-      version_command
-      exit
-      ;;
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --version | -v)
+        version_command
+        exit
+        ;;
 
-    --help | -h)
-      long_usage=yes
-      roulette_usage
-      exit
-      ;;
+      --help | -h)
+        long_usage=yes
+        roulette_usage
+        exit
+        ;;
 
-  esac
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.environment_variables_filter
+
+  env_var_names+=("ROULETTE_DEBUG")
+  env_var_names+=("MPV_GEOMETRY")
+  env_var_names+=("MPV_VOLUME")
 
   # :command.command_filter
   action="root"
@@ -384,7 +413,7 @@ parse_requirements() {
       --debug | -d)
 
         # :flag.case_no_arg
-        args[--debug]=1
+        args['--debug']=1
         shift
         ;;
 
@@ -392,24 +421,24 @@ parse_requirements() {
       --reset)
 
         # :flag.case_no_arg
-        args[--reset]=1
+        args['--reset']=1
         shift
         ;;
 
       -?*)
-        printf "invalid option: %s\n" "$key"
+        printf "invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        if [[ -z ${args[directory]+x} ]]; then
-
-          args[directory]=$1
+        # :argument.case
+        if [[ -z ${args['directory']+x} ]]; then
+          args['directory']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key"
+          printf "invalid argument: %s\n" "$key" >&2
           exit 1
         fi
 
@@ -422,8 +451,7 @@ parse_requirements() {
 
 # :command.initialize
 initialize() {
-  version="1.0.0"
-  long_usage=''
+  declare -g version="1.1.0"
   set -e
 
   # src/initialize.sh
@@ -698,16 +726,24 @@ initialize() {
 
 # :command.run
 run() {
-  declare -A args=()
-  declare -a other_args=()
-  declare -a input=()
+  # :command.globals
+  declare -g long_usage=''
+  declare -g -A args=()
+  declare -g -A deps=()
+  declare -g -a env_var_names=()
+  declare -g -a input=()
+
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
-  if [[ $action == "root" ]]; then
-    root_command
-  fi
+  case "$action" in
+    "root") root_command ;;
+  esac
 }
 
-initialize
-run "$@"
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  # :command.start
+  command_line_args=("$@")
+  initialize
+  run "${command_line_args[@]}"
+fi
